### ISSUE TITLE
Examples should link to absolute module path

### ISSUE THREAD

**Issue by dtest** [GoogleCloudPlatform/terraform-google-cloud-spanner#8]
The examples currently use a relative path to the parent submodule. Here's one instance in the [KMS example](https://github.com/GoogleCloudPlatform/terraform-google-cloud-spanner/blob/main/examples/example_with_kms/main.tf#L47)

It would be good to use remote absolute paths that users could follow along without downloading the repo first.

**Comment by anaik91** [comment]
@dtest the examples are just to show different scenarios how the module can be used .

you dont need to download the module you can also set the source to
git 
```
module "cloud_spanner" {
  source = "git::https://github.com/GoogleCloudPlatform/terraform-google-cloud-spanner"`
  ...
  ...
```
or registry once it available there

```
module "cloud_spanner" {
  source  = "terraform-google-modules/cloud-spanner/google"
  ...
  ...
```

**Comment by dtest** [comment]
Thanks @anaik91 . The reason I opened this is that I think the examples should use the absolute options, rather than the remote. That way people who are maybe not as familiar with modules don't hit a wall when trying to use them. 

Do we have a sense of when/if the module will be on the registry?
